spring:
  application:
    name: bookstore
  datasource:
    url: jdbc:h2:mem:books_db
    driver-class-name: org.h2.Driver
    username: ja
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false



